server:
  port: ${SERVER_PORT:8080}

spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:create-drop}
#      no final update
      show-sql: true
  datasource:
    url: ${MARIADB_URL:jdbc:mysql://localhost:3306/lms}
    username: ${MARIADB_USER:root}
    password: ${MARIADB_PASSWORD:rootPassword}